# Generated by Django 5.1 on 2026-04-30 12:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=150)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("romance", "Romance"),
                            ("comedia", "Comédia"),
                            ("terror", "Terror"),
                            ("fantasia", "Fantasia"),
                            ("cientifico", "Artigo Científico"),
                            ("biografia", "Biografia"),
                            ("historia", "História"),
                            ("tecnologia", "Tecnologia"),
                        ],
                        default="romance",
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "quantidade_total",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantidade_disponivel",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_emprestimo",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_prevista_devolucao", models.DateField()),
                ("data_devolucao", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("devolvido", "Devolvido"),
                            ("atrasado", "Atrasado"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                (
                    "multa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprestimos",
                        to="core.livro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emprestimos",
                        to="core.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empréstimo",
                "verbose_name_plural": "Empréstimos",
                "ordering": ["-data_emprestimo"],
            },
        ),
    ]
